#!/bin/bash
# Demo of interactive coding with the Love-Unlimited CLI

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║         INTERACTIVE CODING WITH LOVE-UNLIMITED CLI               ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "You can use the CLI to code interactively:"
echo ""
echo "  python3 love_cli.py"
echo ""
echo "Then use these commands:"
echo ""
echo "  /to claude    → Ask Claude to write clean, production code"
echo "  /to grok      → Ask Grok for creative solutions & explanations"
echo "  /to swarm     → Ask Swarm for distributed/parallel algorithms"
echo "  /to all       → Get input from ALL THREE AIs at once!"
echo ""
echo "Example session:"
echo "  > /to claude"
echo "  → Now talking to: CLAUDE"
echo "  > Write a function to validate email addresses"
echo "  [CLAUDE]: Here's a robust email validator..."
echo ""
echo "  > /to all"
echo "  → Now talking to: ALL"
echo "  > What's the best way to cache API responses?"
echo "  [CLAUDE]: Use Redis with TTL..."
echo "  [GROK]: Consider in-memory caching with LRU..."
echo "  [SWARM]: Distributed cache across nodes..."
echo ""
echo "="*70
echo "TIP: Use '/to all' to get diverse perspectives on architecture!"
echo "="*70
